import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-neutral">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/wel8ibk.css" />
      </head>
      <body>{children}</body>
    </html>
  );
}
